spring.application.name=payment-billing-service-HCB
server.port=8006

spring.datasource.url=jdbc:mysql://localhost:3306/healthycraftybites
spring.datasource.username=hcb
spring.datasource.password=hcb@123

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
