spring.application.name=api-gateway-project-HCB
server.port=8080


spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:5173
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PATCH,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true

spring.cloud.gateway.server.webflux.routes[0].id=authentication-service-HCB
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8001
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/authenticationservice/**

spring.cloud.gateway.server.webflux.routes[1].id=menu-management-service-HCB
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8002
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/menumanagementservice/**

spring.cloud.gateway.server.webflux.routes[2].id=notification-service-HCB
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8004
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/notificationservice/**

spring.cloud.gateway.server.webflux.routes[3].id=user-service-HCB
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:8003
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/userservice/**

spring.cloud.gateway.server.webflux.routes[4].id=order-service-HCB
spring.cloud.gateway.server.webflux.routes[4].uri=http://localhost:8005
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/orderservice/**

spring.cloud.gateway.server.webflux.routes[5].id=payment-billing-service-HCB
spring.cloud.gateway.server.webflux.routes[5].uri=http://localhost:8006
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/paymentbillingservice/**

spring.cloud.gateway.server.webflux.routes[6].id=analytics-service-HCB
spring.cloud.gateway.server.webflux.routes[6].uri=http://localhost:8007
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/analyticsservice/**