spring.application.name=api-gateway-project-HCB
server.port=8080


spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:5173
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PATCH,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true

spring.cloud.gateway.server.webflux.routes[0].id=authentication-service-HCB
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8001
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/authenticationservice/**

spring.cloud.gateway.server.webflux.routes[1].id=menu-management-service-HCB
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8002
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/menumanagementservice/**